project: AstralDB
authors: ["bumblebee777"]
license: MIT
version: 1.0
language: cpp
standard: c++23
compiler: clang++
project_type: library
project_dirs:
  - sources/Database
  - sources/SQL
  - sources/IO
  - sources/DS
output: bin/libastraldb.a
compiler_flags:
  global: "-Wall -Wextra -Werror -fstack-protector-strong -fpie -Isources -Ithird_party -Itests"
  common: "-Os"
  cpp: "-ffunction-sections -fdata-sections"
  ar: ""
  ld: "-Wl,--stack,8388608"

unit_tests:
  project_dirs:
    - tests
  output: bin/run_tests

subprojects:
  - app
