project: AstralDB
authors: ["bumblebee777"]
license: MIT
compiler: clang++
language: cpp
standard: c++23
project_type: executable
project_dirs: ["sources/"]
output: astraldb
include_paths: ["sources/"]
compiler_flags:
  global: "-O3 -Wall -Wextra -Werror"