project: astraldb
language: cpp
standard: c++23
compiler: clang++
project_type: executable
project_dirs: []
supplementary_sources:
  - ../sources/Program.cxx
output: ../bin/astraldb.exe
compiler_flags:
  global: "-Wall -Wextra -Werror -fstack-protector-strong -fpie -Isources -Ithird_party"
  common: "-Os"
  cpp: "-std=c++23 -ffunction-sections -fdata-sections"
  ld: "-Lbin -lastraldb -Wl,--stack,8388608 -Wl,--gc-sections -s"
