project: astraldb-app
authors: ["bumblebee777"]
license: MIT
version: 2.0
language: cpp
standard: c++23
compiler: clang++
project_type: executable
project_dirs: []
# Resolved from repo root (InsurgeNT compile cwd), not app/.
supplementary_sources:
  - ../sources/Program.cxx
output: ../bin/astraldb.exe
compiler_flags:
  global: "-Wall -Wextra -Werror -fstack-protector-strong -fpie -Isources -Ithird_party -Iinclude -Itests"
  common: "-Os"
  cpp: "-std=c++23 -ffunction-sections -fdata-sections"
  ld: "-Lbin -lastraldb_c -lastraldb_core -Wl,--stack,8388608 -Wl,--gc-sections"
