# AstralDB release profiles, SIMD, and LTO helpers (included from CMakeLists.txt).

option(ASTRALDB_LTO "Enable link-time optimization on Release builds" OFF)
option(ASTRALDB_NATIVE_ARCH "Use -march=native or /arch:AVX2 on speed profile (x86)" OFF)

set(ASTRALDB_RELEASE_PROFILE "size" CACHE STRING "Release tuning: size (default) or speed")
set_property(CACHE ASTRALDB_RELEASE_PROFILE PROPERTY STRINGS size speed)

set(ASTRALDB_SIMD "auto" CACHE STRING "SIMD ISA: auto, off, avx2, sse2, neon")
set_property(CACHE ASTRALDB_SIMD PROPERTY STRINGS auto off avx2 sse2 neon)

function(astraldb_apply_release_profile target)
	if(NOT CMAKE_BUILD_TYPE STREQUAL "Release" AND NOT CMAKE_CONFIGURATION_TYPES)
		return()
	endif()
	if(MSVC)
		if(ASTRALDB_RELEASE_PROFILE STREQUAL "speed")
			target_compile_options(${target} PRIVATE /O2)
		else()
			target_compile_options(${target} PRIVATE /O1 /Gy)
		endif()
	else()
		if(ASTRALDB_RELEASE_PROFILE STREQUAL "speed")
			target_compile_options(${target} PRIVATE -O3)
		else()
			target_compile_options(${target} PRIVATE -Os)
		endif()
		if(NOT MSVC)
			target_compile_options(${target} PRIVATE -ffunction-sections -fdata-sections)
			target_link_options(${target} PRIVATE -Wl,--gc-sections)
		endif()
	endif()
endfunction()

function(astraldb_apply_simd target)
	if(ASTRALDB_SIMD STREQUAL "off")
		return()
	endif()
	if(ASTRALDB_SIMD STREQUAL "avx2")
		if(MSVC)
			target_compile_options(${target} PRIVATE /arch:AVX2)
		else()
			target_compile_options(${target} PRIVATE -mavx2 -mfma)
		endif()
		return()
	endif()
	if(ASTRALDB_SIMD STREQUAL "sse2")
		if(MSVC)
			target_compile_options(${target} PRIVATE /arch:SSE2)
		else()
			target_compile_options(${target} PRIVATE -msse2)
		endif()
		return()
	endif()
	if(ASTRALDB_SIMD STREQUAL "neon")
		if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm|aarch64|ARM64")
			return()
		endif()
		return()
	endif()
	# auto
	if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm|aarch64|ARM64")
		return()
	endif()
	if(ASTRALDB_RELEASE_PROFILE STREQUAL "speed" AND ASTRALDB_NATIVE_ARCH)
		if(MSVC)
			target_compile_options(${target} PRIVATE /arch:AVX2)
		else()
			target_compile_options(${target} PRIVATE -march=native)
		endif()
	elseif(NOT MSVC)
		target_compile_options(${target} PRIVATE -mavx2 -mfma)
	endif()
endfunction()

function(astraldb_apply_lto target)
	if(NOT ASTRALDB_LTO)
		return()
	endif()
	if(MSVC)
		set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
	else()
		target_compile_options(${target} PRIVATE -flto=thin)
		target_link_options(${target} PRIVATE -flto=thin)
	endif()
endfunction()

function(astraldb_apply_target_options target)
	astraldb_apply_release_profile(${target})
	astraldb_apply_simd(${target})
	astraldb_apply_lto(${target})
endfunction()
